/*
        {sectioned[0].map(single => 

        <Card
           projectTitle       ={single.projectTitle}
           projectTags        ={single.projectTags}
           backSummary        ={single.backSummary}
           frontSummary       ={single.frontSummary}
           liveSiteHref       ={single.liveSiteHref}
           caption            ={single.caption}
           imgLinkThmb        ={single.imgLinkThmb}
           imgLink            ={single.imgLink[0]}
           altTxt             ={single.altTxt}
           imageSet           ={single.imageSet}
           caption2           ={single.caption}
           key                ={single.projectTitle}
            />
        
          )}
*?

projectTags:["",""],
backSummary:"",
frontSummary:"",



      export const propData =[  
  {  
    imgLink:[  
      "http://res.cloudinary.com/tor020/image/upload/v1503378889/PortfolioVer1%20Full/home_exd0jj.png",
      "https://res.cloudinary.com/tor020/image/upload/v1503378875/PortfolioVer1%20Full/b_qeep7j.png"
    ],
    projectTitle:"KF2Calc",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1503378915/PortfolioVer1%20Thmb/home_up0keu.png",
    imageSet:"KF2Calc",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/Killing-Floor-2-Calculator/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1503378906/PortfolioVer1%20Full/Todo6_n6vsac.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504050534/PortfolioVer1%20Full/todo_code.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504050540/PortfolioVer1%20Full/todo_code_pt1.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504050544/PortfolioVer1%20Full/todocode_pt2.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504050548/PortfolioVer1%20Full/todocode_pt3.png"
    ],
    projectTitle:"ToDoList",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1503378906/PortfolioVer1%20Full/Todo6_n6vsac.png",
    imageSet:"ToDoList",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/TodoWebApp/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1504058445/PortfolioVer1%20Full/wphome.png",
      "http://www.kcwebdevoh.online/home/front-end-vs-back-end-vs-fullstack/"
    ],
    projectTitle:"WPressSolutions",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1504058444/PortfolioVer1%20Thmb/wphome.thmb.png",
    imageSet:"WPressSolutions",
    caption:"",
    altTxt:"",
    liveSiteHref:"http://www.kcwebdevoh.online",

  },
  {  
    imgLink:[  
      " https://res.cloudinary.com/tor020/image/upload/v1504224290/PortfolioVer1%20Full/screencapture-tor020-github-io-PortfolioRound2-1504222631682.png",
      ""
    ],
    projectTitle:"PrevPortfolio2",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1504224341/PortfolioVer1%20Thmb/screencapture-tor020-github-io-PortfolioRound2-1504222631682.thmb.png",
    imageSet:"PrevPortfolio2",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/PortfolioRound2/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1504224831/PortfolioVer1%20Full/screencapture-tor020-github-io-1504224753320.png",
      ""
    ],
    projectTitle:"BootstrapPortfolio",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1504222180/PortfolioVer1%20Thmb/bootstrapportfolio.png",
    imageSet:"BootstrapPortfolio",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/BootstrapPort/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1503378893/PortfolioVer1%20Full/pong5_qi2xwv.png",
      "https://res.cloudinary.com/tor020/image/upload/v1503378892/PortfolioVer1%20Full/pong1_fe669s.png"
    ],
    projectTitle:"PongReplica",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1503378916/PortfolioVer1%20Thmb/pong5_kaxvjx.png",
    imageSet:"PongReplica",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/Pong/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1504083019/PortfolioVer1%20Full/screencapture-tor020-github-io-chartjs-1504082822889.png",
      "https://res.cloudinary.com/tor020/image/upload/v1503378889/PortfolioVer1%20Full/json1_wvgz0b.png",
      ""
    ],
    projectTitle:"Chartjs",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1504083013/PortfolioVer1%20Thmb/screencapture-tor020-github-io-chartjs-1504082822889.thmb.png",
    imageSet:"Chartjs",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/chartjs/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1503378890/PortfolioVer1%20Full/json3_c6y4hz.png",
      "https://res.cloudinary.com/tor020/image/upload/v1503378889/PortfolioVer1%20Full/json1_wvgz0b.png"
    ],
    projectTitle:"AjaxwithFetch",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1503378915/PortfolioVer1%20Thmb/json3_r4cdch.png",
    imageSet:"AjaxwithFetch",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/jsontutorial",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1503378908/PortfolioVer1%20Thmb/flexLay2_ozmsnt.png",
      "https://res.cloudinary.com/tor020/image/upload/v1503378915/PortfolioVer1%20Thmb/flexLay1_opv48f.png"
    ],
    projectTitle:"FlexPane",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1503378914/PortfolioVer1%20Thmb/flexLay2_ptxg8a.png",
    imageSet:"FlexPane",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/flexframelayout/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1504130038/PortfolioVer1%20Full/screencapture-tor020-github-io-Sandt-1504129665265_s8sr1o.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504130037/PortfolioVer1%20Full/screencapture-tor020-github-io-Sandt-1504129671584_mcxoao.png"
    ],
    projectTitle:"CanvasColor",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1504130036/PortfolioVer1%20Thmb/screencapture-tor020-github-io-Sandt-1504129665265.thmb_o8r5ny.png",
    imageSet:"CanvasColor",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/Sandt/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1503378896/PortfolioVer1%20Full/projectarch1_vrwugi.png",
      ""
    ],
    projectTitle:"ProjectArchives",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1503378916/PortfolioVer1%20Thmb/projectarch1_llgeyz.png",
    imageSet:"ProjectArchives",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/Online_Archiv/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1503378899/PortfolioVer1%20Full/Matrix_ekvbzj.png",
      ""
    ],
    projectTitle:"MatrixNumberFall",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1503378916/PortfolioVer1%20Thmb/Matrix_yctjz1.png",
    imageSet:"MatrixNumberFall",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/Matrix-Modified/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1503378874/PortfolioVer1%20Full/clk_o92gjr.png",
      "https://res.cloudinary.com/tor020/image/upload/v1503378874/PortfolioVer1%20Full/clk2_uq21z1.png"
    ],
    projectTitle:"Css3Clock",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1503378910/PortfolioVer1%20Thmb/clk_xujakz.png",
    imageSet:"Css3Clock",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/verbose-octo-lamp/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1504130942/BulmaThemeBP_mt6ahs.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504130942/BulmaThemeBP2_tqdtm4.png"
    ],
    projectTitle:"BulmaCssTester",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1504130942/BulmaThemeBP.thmb_ynfr9m.png",
    imageSet:"BulmaCssTester",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/Bulma-Boilerplate/",

  },
  {  
    imgLink:[  
      "https://res.cloudinarycom/tor020/image/upload/v1504477286/PortfolioVer1%20Full/screencapture-file-C-Users-Kevin-Desktop-LIVE-PROJECTS-CSSvariableTutorial-index-html-1504477079643_aa4w1a.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504477286/PortfolioVer1%20Full/screencapture-file-C-Users-Kevin-Desktop-LIVE-PROJECTS-CSSvariableTutorial-index-html-1504477122240_z3iw27.png"
    ],
    projectTitle:"CssVariables",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1504477278/PortfolioVer1%20Thmb/screencapture-file-C-Users-Kevin-Desktop-LIVE-PROJECTS-CSSvariableTutorial-index-html-1504477079643.thmb_uq7dex.png",
    imageSet:"CssVariables",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/CSSVariableTutorial/",

  },
  {  
    imgLink:[  
      "https://res.cloudinary.com/tor020/image/upload/v1504085029/screencapture-tor020-github-io-commonresource-1504084892842_k8lj0h.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504085031/screencapture-tor020-github-io-commonresource-1504084899889_xu5ia2.png",
      "https://res.cloudinary.com/tor020/image/upload/v1504085031/screencapture-tor020-github-io-commonresource-1504084911310_x32zho.png"
    ],
    projectTitle:"CommonResources",
    imgLinkThmb:"https://res.cloudinary.com/tor020/image/upload/v1504085119/screencapture-tor020-github-io-commonresource-1504084899889.thmb_mfdrm0.png",
    imageSet:"CommonResources",
    caption:"",
    altTxt:"",
    liveSiteHref:"https://tor020.github.io/commonresource/",

  },
  {  
    imgLink:[  
      "",
      ""
    ],
    projectTitle:"HomePageApp",
    imgLinkThmb:"",
    imageSet:"HomePageApp",
    caption:"",
    altTxt:"",
    liveSiteHref:"",

  },
  {  
    imgLink:[  
      "",
      ""
    ],
    projectTitle:"DimenciaPortfolio",
    imgLinkThmb:"",
    imageSet:"DimenciaPortfolio",
    caption:"",
    altTxt:"",
    liveSiteHref:"",

  }
]

*/